# File @generated by holbertonschool-AirBnB_clone/AUTHORS.txt. DO NOT EDIT.
# This file lists all contributors to the repository.
# See hack/generate-authors.sh to make modifications.

# Open the file in write mode
with open('AUTHORS.txt', 'w') as file:
    # Write author names to the file
    file.write("Khadija Aassi\n")
    file.write("Amandine Kemp\n")

# Print a message once writing is done
print("The 'authors.txt' file has been successfully generated.")
